/* FootGame simulation core.  It deliberately has no browser dependencies. */
(function (root, factory) {
  const api = factory();
  if (typeof module !== 'undefined') module.exports = api;
  root.MatchEngine = api.MatchEngine; root.simulateMatch = api.simulateMatch; root.simulateMatches = api.simulateMatches;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const W=1280,H=720, FIELD={left:88,right:1192,top:62,bottom:658}, GOAL={top:286,bottom:434,depth:44};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), sigmoid=v=>1/(1+Math.exp(-v));
  const len=(x,y)=>Math.hypot(x,y), norm=(x,y)=>{const d=len(x,y)||1;return{x:x/d,y:y/d}};
  const dist=(a,b)=>len(a.x-b.x,a.y-b.y);
  class RNG { constructor(seed=1){this.state=(Number(seed)>>>0)||1} next(){let t=this.state+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296} gaussian(){let u=this.next()||1e-9,v=this.next();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)} }
  const sampleGaussian=rng=>rng.gaussian();
  function sampleExecution(skill,context=0,opposition=0,minVariance=5,rng=new RNG()) { const sd=Math.max(minVariance,24-clamp(skill,0,100)*.16); const variance=rng.gaussian()*sd; return { value:skill+context-opposition+variance, variance, deviation:sd }; }
  const names={blue:['NOA','MILO','SACHA','ELIOTT','YANIS'],red:['LÉO','NINO','TOM','AXEL','ENZO']};
  const formation={blue:[[120,360],[345,230],[345,490],[620,285],[610,440]],red:[[1160,360],[935,230],[935,490],[660,285],[670,440]]};
  const attrs={blue:[[61,68,52,64,35,74,86,78],[76,72,70,62,51,82,18,84],[69,86,82,91,68,67,12,88],[83,78,88,79,87,45,9,79],[90,71,84,68,80,38,8,73]],red:[[66,74,58,72,32,71,89,75],[72,68,67,65,47,86,14,87],[81,77,76,75,62,72,10,82],[75,88,85,90,74,56,11,84],[87,69,86,71,89,34,7,76]]};
  function makePlayer(team,index,override){const [vitesse,passe,technique,vision,tir,defense,gardien,enduranceStat]=attrs[team][index];const [x,y]=formation[team][index];const a={vitesse,passe,technique,vision,tir,defense,gardien,enduranceStat,...(override||{})}; Object.keys(a).forEach(k=>a[k]=clamp(a[k],0,100)); return {team,index,name:names[team][index],number:[1,4,8,10,11][index],keeper:index===0,x,y,vx:0,vy:0,radius:index===0?19:17,facingX:team==='blue'?1:-1,facingY:0,energyCurrent:1,stamina:1,attributes:a,actionCooldown:.2,decisionCooldown:0,tackleCooldown:0,dribbleCooldown:0,imbalance:0,hasBallTime:0,actionActuelle:'SE_REPLACER',actionTarget:null,actionStartedAt:0,lastDirectionChangeAt:0,carryStartedAt:0,matchStats:{goals:0,assists:0,shots:0,shotsOnTarget:0,shotsOffTarget:0,shotsBlocked:0,passesAttempted:0,passesCompleted:0,tackles:0,tacklesWon:0,saves:0,savesParried:0,losses:0,interceptions:0,failedControls:0,touches:0,distanceConduite:0,conduitesProgressives:0,dribblesTentes:0,dribblesReussis:0,dribblesRates:0,defenseursElimines:0,debordements:0,repiquages:0,ballonsPerdusEnConduite:0}}}
  class MatchEngine {
    constructor(config={}) { this.config=config; this.seed=config.seed??12345;this.rng=new RNG(this.seed);this.fixedDt=config.fixedDt||1/60;this.duration=config.duration||180;this.events=[];this.eventHistory=[];this.time=0;this.finished=false;this.score={blue:0,red:0};this.stats={blue:this.teamStats(),red:this.teamStats()};this.possession={blue:0,red:0};this.players=['blue','red'].flatMap(t=>[0,1,2,3,4].map(i=>makePlayer(t,i,config.teams?.[t]?.[i])));this.freeze=.6;this.kickoff('blue',true); }
    teamStats(){return {shots:0,passes:0,tirsCadres:0,tirsNonCadres:0,tirsBloques:0,ballonsPerdus:0,interceptions:0,controlesRates:0,paradesCaptees:0,paradesRepoussees:0,distanceConduite:0,conduitesProgressives:0,dribblesTentes:0,dribblesReussis:0,dribblesRates:0,defenseursElimines:0,debordements:0,repiquages:0,ballonsPerdusEnConduite:0};}
    emit(type,data={}){const e={type,time:this.time,...data};this.events.push(e);this.eventHistory.push(e);if(this.eventHistory.length>400)this.eventHistory.shift();}
    kickoff(team,opening=false){for(const p of this.players){const q=formation[p.team][p.index];p.x=q[0];p.y=q[1];p.vx=p.vy=0;p.hasBallTime=0}const k=this.players.find(p=>p.team===team&&p.index===3),s=this.players.find(p=>p.team===team&&p.index===4),d=team==='blue'?1:-1;k.x=W/2-d*15;k.y=H/2;s.x=W/2-d*80;s.y=H/2+50;this.ball={x:W/2,y:H/2,vx:0,vy:0,radius:8,owner:k,pickupDelay:.25,lastTouch:team,passFrom:null,lastShooter:null,assistCandidate:null,assistTime:0};k.matchStats.touches++;this.freeze=opening?.12:1.3;this.emit('KICKOFF',{team});}
    isFinished(){return this.finished} getState(){return {time:this.time,remaining:Math.max(0,this.duration-this.time),score:{...this.score},stats:this.stats,possession:this.possession,players:this.players,ball:this.ball,finished:this.finished}};
    getResult(){const ratings={};for(const p of this.players)ratings[`${p.team}-${p.index}`]=this.rating(p);return {score:{...this.score},vainqueur:this.score.blue===this.score.red?'draw':this.score.blue>this.score.red?'blue':'red',statistiques:{equipes:this.stats,individuelles:this.players.map(p=>({name:p.name,team:p.team,...p.matchStats}))},notesJoueurs:ratings,buteurs:this.players.filter(p=>p.matchStats.goals).map(p=>({name:p.name,goals:p.matchStats.goals})),passeurs:this.players.filter(p=>p.matchStats.assists).map(p=>({name:p.name,assists:p.matchStats.assists})),evenements:this.eventHistory,seed:this.seed};}
    rating(p){const s=p.matchStats, missed=s.passesAttempted-s.passesCompleted;return +clamp(6+s.goals*1.05+s.assists*.62+s.saves*.16+s.tacklesWon*.13+s.passesCompleted*.018-missed*.025-(s.tackles-s.tacklesWon)*.035-s.shotsOffTarget*.035-s.losses*.045-s.failedControls*.04,5,10).toFixed(1)}
    nearest(team,target,noKeeper=false){return this.players.filter(p=>p.team===team&&(!noKeeper||!p.keeper)).sort((a,b)=>dist(a,target)-dist(b,target))[0]}
    pressure(p){let v=Infinity;for(const q of this.players)if(q.team!==p.team)v=Math.min(v,dist(p,q));return v}
    blockers(a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy||1;return this.players.filter(p=>p.team!==a.team&&!p.keeper).filter(p=>{const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l2,0,1);return t>.08&&t<.92&&len(p.x-(a.x+dx*t),p.y-(a.y+dy*t))<34}).length}
    fatigue(p){return (1-p.energyCurrent)*18}
    getNearestOpponentDistance(p){return this.pressure(p)}
    getPressureAround(p,radius=110){return this.players.filter(q=>q.team!==p.team&&dist(q,p)<radius).length}
    getProgressTowardOpponentGoal(p,direction){return direction.x*(p.team==='blue'?1:-1)}
    isLaneOpen(p,direction,distance=120){const end={x:p.x+direction.x*distance,y:p.y+direction.y*distance};return this.blockers(p,end)===0&&this.players.filter(q=>q.team!==p.team).every(q=>dist(q,end)>30)}
    evaluateSpaceAhead(p,direction){const dir=norm(direction.x,direction.y),end={x:clamp(p.x+dir.x*135,FIELD.left+20,FIELD.right-20),y:clamp(p.y+dir.y*135,FIELD.top+20,FIELD.bottom-20)},near=this.players.filter(q=>q.team!==p.team).reduce((v,q)=>Math.min(v,dist(q,end)),220),sideline=Math.min(end.y-FIELD.top,FIELD.bottom-end.y);return near*.42+this.getProgressTowardOpponentGoal(p,dir)*55+Math.min(sideline,80)*.18-this.blockers(p,end)*25}
    chooseCarryDirection(p){const forward=p.team==='blue'?1:-1,choices=[{x:forward,y:0},{x:forward,y:-.55},{x:forward,y:.55},{x:0,y:-1},{x:0,y:1},{x:-forward*.35,y:0}];let best=choices[0],score=-Infinity;for(const c of choices){const s=this.evaluateSpaceAhead(p,c)+this.rng.gaussian()*4;if(s>score){score=s;best=norm(c.x,c.y)}}return best}
    setAction(p,action,target=null,duration=.7){p.actionActuelle=action;p.actionTarget=target;p.actionStartedAt=this.time;p.decisionCooldown=duration;if(['CONDUIRE','PROGRESSER','DEBORDER','REPIQUER'].includes(action)){p.carryStartedAt=this.time;p.matchStats.conduitesProgressives++;this.stats[p.team].conduitesProgressives++;if(action==='DEBORDER'){p.matchStats.debordements++;this.stats[p.team].debordements++}if(action==='REPIQUER'){p.matchStats.repiquages++;this.stats[p.team].repiquages++}this.emit(action==='DEBORDER'?'WING_RUN_START':action==='REPIQUER'?'CUT_INSIDE':'BALL_CARRY_START',{team:p.team,player:p.name,action})}}
    target(p){const dir=p.team==='blue'?1:-1,o=this.ball.owner,own=o?.team===p.team,opp=o&&o.team!==p.team;if(p.keeper){const gx=p.team==='blue'?FIELD.left+30:FIELD.right-30,danger=p.team==='blue'?this.ball.x<FIELD.left+260:this.ball.x>FIELD.right-260;if(!o&&danger&&dist(p,this.ball)<115+p.attributes.gardien*.75)return{x:this.ball.x,y:this.ball.y};return{x:gx,y:clamp(this.ball.y,GOAL.top+26,GOAL.bottom-26)}}if(o===p&&p.actionTarget)return p.actionTarget;const closest=this.nearest(p.team,this.ball,true);if(!o&&closest===p){p.actionActuelle='RECUPERER';return{x:this.ball.x,y:this.ball.y}}if(opp&&closest===p){p.actionActuelle='PRESSER';return{x:this.ball.x-dir*22,y:this.ball.y}}const base=formation[p.team][p.index],attackingRun=own?(p.index>=2?170:105):0;p.actionActuelle=own?'APPELER_BALLON':'SE_REPLACER';return{x:clamp(base[0]+(this.ball.x-W/2)*.36+dir*(own?140+attackingRun:0),FIELD.left+55,FIELD.right-55),y:clamp(base[1]+(this.ball.y-H/2)*.21,FIELD.top+42,FIELD.bottom-42)}}
    step(dt=this.fixedDt){if(this.finished)return this.getState();dt=Math.min(dt,.1);this.events=[];this.time+=dt;if(this.time>=this.duration){this.finished=true;this.emit('MATCH_END',{score:{...this.score}});return this.getState()}if(this.freeze>0){this.freeze-=dt;if(this.freeze<=0&&this.pendingKickoff){const t=this.pendingKickoff;this.pendingKickoff=null;this.kickoff(t)}return this.getState()}this.updatePlayers(dt);this.updateBall(dt);return this.getState()}
    updatePlayers(dt){for(const p of this.players){p.actionCooldown=Math.max(0,p.actionCooldown-dt);p.decisionCooldown=Math.max(0,p.decisionCooldown-dt);p.tackleCooldown=Math.max(0,p.tackleCooldown-dt);p.dribbleCooldown=Math.max(0,p.dribbleCooldown-dt);p.imbalance=Math.max(0,p.imbalance-dt);if(this.ball.owner===p)this.decide(p);const t=this.target(p),dx=t.x-p.x,dy=t.y-p.y,d=len(dx,dy),chase=(!this.ball.owner&&dist(p,this.ball)<200)||(this.ball.owner?.team!==p.team&&dist(p,this.ball)<160),drain=chase?(.075-p.attributes.enduranceStat*.00045):-(.035+p.attributes.enduranceStat*.00035);p.energyCurrent=clamp(p.energyCurrent-drain*dt,.25,1);p.stamina=p.energyCurrent;if(d>5){const n=norm(dx,dy),f=.76+p.energyCurrent*.24,max=(p.keeper?185:chase?216:177)*(.72+p.attributes.vitesse/250)*f,acc=(p.keeper?690+p.attributes.gardien*1.1:570+p.attributes.vitesse*1.7)*f*(p.imbalance?.45:1);p.vx+=n.x*acc*dt;p.vy+=n.y*acc*dt;const sp=len(p.vx,p.vy);if(sp>max){p.vx=p.vx/sp*max;p.vy=p.vy/sp*max}p.facingX=n.x;p.facingY=n.y}const old={x:p.x,y:p.y};p.vx*=Math.pow(.0018,dt);p.vy*=Math.pow(.0018,dt);p.x=clamp(p.x+p.vx*dt,FIELD.left+p.radius,FIELD.right-p.radius);p.y=clamp(p.y+p.vy*dt,FIELD.top+p.radius,FIELD.bottom-p.radius);if(this.ball.owner===p&&['CONDUIRE','PROGRESSER','DRIBBLER','DEBORDER','REPIQUER'].includes(p.actionActuelle)){const moved=dist(old,p);p.matchStats.distanceConduite+=moved;this.stats[p.team].distanceConduite+=moved}}for(let i=0;i<this.players.length;i++)for(let j=i+1;j<this.players.length;j++)this.collidePlayers(this.players[i],this.players[j])}
    decide(p){p.hasBallTime+=this.fixedDt;if(p.decisionCooldown>0)return;const gx=p.team==='blue'?FIELD.right:FIELD.left,gd=Math.abs(gx-p.x),occasion=this.occasion(p),target=this.bestPass(p),pressure=this.getNearestOpponentDistance(p),direction=this.chooseCarryDirection(p),space=this.evaluateSpaceAhead(p,direction),wing=Math.min(p.y-FIELD.top,FIELD.bottom-p.y)<110;if(pressure<75&&p.dribbleCooldown<=0&&p.attributes.technique>48&&space>45&&this.rng.next()<.18){this.dribble(p,direction);return}const shotScore=p.attributes.tir*.45+occasion+p.attributes.vision*.1-this.fatigue(p),passScore=(target?.passScore||0)+p.attributes.vision*.25+22,carryScore=space+p.attributes.technique*.14+p.attributes.vitesse*.09-pressure*.25;if(gd<330+p.attributes.tir*2&&shotScore>76){this.shoot(p,occasion);return}if(carryScore>passScore+6&&gd>230){let action=wing?'DEBORDER':'PROGRESSER';if(wing&&direction.y*(p.y-H/2)<0&&this.rng.next()<.35)action='REPIQUER';const point={x:clamp(p.x+direction.x*150,FIELD.left+30,FIELD.right-30),y:clamp(p.y+direction.y*150,FIELD.top+30,FIELD.bottom-30)};this.setAction(p,action,point,.75);return}if(target&&passScore>34){this.pass(p,target);return}this.setAction(p,'CONDUIRE',{x:clamp(p.x+direction.x*95,FIELD.left+30,FIELD.right-30),y:clamp(p.y+direction.y*95,FIELD.top+30,FIELD.bottom-30)},.52)}
    occasion(p){const gx=p.team==='blue'?FIELD.right:FIELD.left, angle=100-Math.abs(p.y-H/2)*.42,pressure=Math.max(0,115-this.pressure(p)),ob=this.blockers(p,{x:gx,y:H/2})*17,pass=this.bestPass(p)?9:0;return angle*.32+Math.max(0,280-Math.abs(gx-p.x))*.22-pressure*.32-ob-pass}
    bestPass(p){const dir=p.team==='blue'?1:-1;let best=null,score=-Infinity;for(const m of this.players.filter(q=>q.team===p.team&&q!==p&&!q.keeper)){const d=dist(p,m),risk=this.blockers(p,m)*18,progress=(m.x-p.x)*dir,s=p.attributes.vision*.40+this.pressure(m)*.20+progress*.065-d*.028-risk+this.rng.gaussian()*3;if(s>score){score=s;best=m}}if(best)best.passScore=score;return score>.3?best:null}
    dribble(p,direction){const defender=this.players.filter(q=>q.team!==p.team&&!q.keeper).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(!defender)return;const rel=len(defender.vx-p.vx,defender.vy-p.vy),pos=clamp(18-dist(defender,p)*.22+rel*.025+(defender.x-p.x)*(p.team==='blue'?-1:1)*.08,-18,18),a=sampleExecution(p.attributes.technique*.55+p.attributes.vitesse*.20+p.attributes.vision*.10+p.energyCurrent*10,pos,this.fatigue(p),6,this.rng),b=sampleExecution(defender.attributes.defense*.55+defender.attributes.vitesse*.15+defender.attributes.vision*.15+pos,-this.fatigue(defender),0,6,this.rng),chance=clamp(sigmoid((a.value-b.value)/14),.16,.78),roll=this.rng.next();p.dribbleCooldown=1.25;p.matchStats.dribblesTentes++;this.stats[p.team].dribblesTentes++;this.emit('DRIBBLE_ATTEMPT',{team:p.team,player:p.name,opponent:defender.name,attackerScore:a.value,defenderScore:b.value,chance,roll,direction});if(roll<chance*.72){p.matchStats.dribblesReussis++;p.matchStats.defenseursElimines++;this.stats[p.team].dribblesReussis++;this.stats[p.team].defenseursElimines++;defender.imbalance=.7;defender.tackleCooldown=1.15;const point={x:clamp(p.x+direction.x*165,FIELD.left+25,FIELD.right-25),y:clamp(p.y+direction.y*165,FIELD.top+25,FIELD.bottom-25)};this.setAction(p,'DRIBBLER',point,.65);this.emit('DRIBBLE_SUCCESS',{team:p.team,player:p.name,opponent:defender.name,chance,roll});this.emit('PLAYER_BEATEN',{team:p.team,player:defender.name});return}if(roll<chance){p.matchStats.dribblesReussis++;this.stats[p.team].dribblesReussis++;this.setAction(p,'CONDUIRE',{x:clamp(p.x+direction.x*65,FIELD.left+25,FIELD.right-25),y:clamp(p.y+direction.y*65,FIELD.top+25,FIELD.bottom-25)},.45);this.emit('DRIBBLE_SUCCESS',{team:p.team,player:p.name,partial:true,chance,roll});return}p.matchStats.dribblesRates++;p.matchStats.losses++;p.matchStats.ballonsPerdusEnConduite++;this.stats[p.team].dribblesRates++;this.stats[p.team].ballonsPerdusEnConduite++;this.stats[p.team].ballonsPerdus++;this.ball.owner=null;this.ball.x=p.x+direction.x*(p.radius+18);this.ball.y=p.y+direction.y*(p.radius+18);this.ball.vx=direction.x*180;this.ball.vy=direction.y*180;this.ball.pickupDelay=.15;this.emit('DRIBBLE_FAILED',{team:p.team,player:p.name,opponent:defender.name,chance,roll})}
    release(p,dx,dy,speed,type,meta={}){if(this.ball.owner!==p)return;if(['CONDUIRE','PROGRESSER','DRIBBLER','DEBORDER','REPIQUER'].includes(p.actionActuelle))this.emit('BALL_CARRY_END',{team:p.team,player:p.name,action:p.actionActuelle});p.actionActuelle=type==='shot'?'TIRER':'PASSER';p.actionTarget=null;const n=norm(dx||p.facingX,dy||p.facingY),b=this.ball;b.owner=null;b.x=p.x+n.x*(p.radius+11);b.y=p.y+n.y*(p.radius+11);b.vx=n.x*speed+p.vx*.35;b.vy=n.y*speed+p.vy*.35;b.pickupDelay=type==='shot'?.18:.1;b.lastTouch=p.team;b.passFrom=type==='pass'?p:null;if(type==='shot')b.lastShooter=p;p.actionCooldown=type==='shot'?.45:.25;p.hasBallTime=0;this.emit(type==='shot'?'SHOT':'PASS_ATTEMPT',{team:p.team,player:p.name,...meta})}
    pass(p,target){const d=dist(p,target),pressure=Math.max(0,105-this.pressure(p)),blockers=this.blockers(p,target),e=sampleExecution(p.attributes.passe*.65+p.attributes.technique*.25+p.attributes.vision*.1,-this.fatigue(p),pressure*.25+d*.055,5,this.rng),error=clamp(118-e.value+blockers*13,5,92),tx=target.x+target.vx*.18+this.rng.gaussian()*error*.42,ty=target.y+target.vy*.18+this.rng.gaussian()*error*.42;p.matchStats.passesAttempted++;this.stats[p.team].passes++;this.release(p,tx-p.x,ty-p.y,390+clamp(e.value,25,110)*1.55,'pass',{target:target.name,skill:p.attributes.passe,context:-d*.055,opposition:pressure,variance:e.variance,score:e.value})}
    shoot(p,occasion){const gx=p.team==='blue'?FIELD.right+25:FIELD.left-25,e=sampleExecution(p.attributes.tir*.65+p.attributes.technique*.25+p.attributes.vision*.1+occasion,-this.fatigue(p),0,7,this.rng),inacc=clamp(146-e.value,18,118),ty=H/2+this.rng.gaussian()*inacc*.55, on=ty>GOAL.top+8&&ty<GOAL.bottom-8;p.matchStats.shots++;this.stats[p.team].shots++;if(on){p.matchStats.shotsOnTarget++;this.stats[p.team].tirsCadres++;this.emit('SHOT_ON_TARGET',{team:p.team,player:p.name})}else{p.matchStats.shotsOffTarget++;this.stats[p.team].tirsNonCadres++;this.emit('SHOT_OFF_TARGET',{team:p.team,player:p.name})}this.release(p,gx-p.x,ty-p.y,570+clamp(e.value,20,115)*2.7,'shot',{skill:p.attributes.tir,context:occasion,opposition:this.pressure(p),variance:e.variance,score:e.value})}
    collidePlayers(a,b){const dx=b.x-a.x,dy=b.y-a.y,d=len(dx,dy)||.01,min=a.radius+b.radius-2;if(d>=min)return;const nx=dx/d,ny=dy/d,o=(min-d)*.5;a.x-=nx*o;a.y-=ny*o;b.x+=nx*o;b.y+=ny*o;if(a.team!==b.team&&this.ball.owner&&(this.ball.owner===a||this.ball.owner===b)){const owner=this.ball.owner,ch=owner===a?b:a;if(ch.tackleCooldown<=0)this.tackle(ch,owner)}}
    tackle(ch,owner){ch.matchStats.tackles++;ch.tackleCooldown=.62;const rel=len(ch.vx-owner.vx,ch.vy-owner.vy),behind=(ch.x-owner.x)*(owner.team==='blue'?1:-1)>0?-12:8,pos=clamp(35-dist(ch,owner)+rel*.04+behind,-16,20),a=sampleExecution(ch.attributes.defense*.65+ch.attributes.vitesse*.15+ch.attributes.vision*.1+pos,-this.fatigue(ch),0,6,this.rng),b=sampleExecution(owner.attributes.technique*.55+owner.attributes.vitesse*.2+owner.attributes.vision*.1+owner.energyCurrent*10,0,0,6,this.rng),chance=clamp(sigmoid((a.value-b.value)/15),.12,.82),won=this.rng.next()<chance;this.emit(won?'TACKLE_WON':'TACKLE_LOST',{team:ch.team,player:ch.name,skill:ch.attributes.defense,opposition:b.value,context:pos,variance:a.variance,chance});if(won){ch.matchStats.tacklesWon++;this.ball.owner=null;this.ball.assistCandidate=null;this.ball.passFrom=null;this.ball.lastShooter=null;const n=norm(owner.x-ch.x,owner.y-ch.y);this.ball.x=owner.x+n.x*22;this.ball.y=owner.y+n.y*22;this.ball.vx=n.x*170+owner.vx;this.ball.vy=n.y*170+owner.vy;this.ball.pickupDelay=.18}else{ch.imbalance=.42;ch.tackleCooldown=1.05;ch.vx*=.25;ch.vy*=.25}}
    updateBall(dt){const b=this.ball;b.pickupDelay=Math.max(0,b.pickupDelay-dt);if(b.owner){const p=b.owner,n=norm(p.facingX|| (p.team==='blue'?1:-1),p.facingY);b.x+=(p.x+n.x*(p.radius+9)-b.x)*clamp(dt*18,0,1);b.y+=(p.y+n.y*(p.radius+9)-b.y)*clamp(dt*18,0,1);b.vx=p.vx;b.vy=p.vy;this.possession[p.team]+=dt;return}b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=Math.pow(.38,dt);b.vy*=Math.pow(.38,dt);if(b.y-b.radius<FIELD.top){b.y=FIELD.top+b.radius;b.vy=Math.abs(b.vy)*.72}if(b.y+b.radius>FIELD.bottom){b.y=FIELD.bottom-b.radius;b.vy=-Math.abs(b.vy)*.72}const mouth=b.y>GOAL.top+4&&b.y<GOAL.bottom-4;if(!mouth){if(b.x-b.radius<FIELD.left){b.x=FIELD.left+b.radius;b.vx=Math.abs(b.vx)*.72}if(b.x+b.radius>FIELD.right){b.x=FIELD.right-b.radius;b.vx=-Math.abs(b.vx)*.72}}if(mouth&&b.x<FIELD.left-GOAL.depth*.55)this.goal('red');if(mouth&&b.x>FIELD.right+GOAL.depth*.55)this.goal('blue');if(b.pickupDelay<=0)for(const p of [...this.players].sort((a,c)=>dist(a,b)-dist(c,b))){const range=p.radius+(p.keeper?7+p.attributes.gardien*.11:10),limit=p.keeper?530+p.attributes.gardien*3:400+p.attributes.passe*.8;if(dist(p,b)<range&&len(b.vx,b.vy)<limit){this.take(p);break}}}
    take(p){const b=this.ball,passer=b.passFrom,shooter=b.lastShooter,speed=len(b.vx,b.vy);if(!p.keeper&&passer&&passer.team===p.team){const pressure=Math.max(0,90-this.pressure(p)),angle=Math.max(0,-(norm(b.vx,b.vy).x*p.facingX+norm(b.vx,b.vy).y*p.facingY)),difficulty=Math.max(0,(speed-210)/7)+pressure*.45+angle*14,e=sampleExecution(p.attributes.technique*.65+p.attributes.passe*.15+p.attributes.vision*.1+p.energyCurrent*10,-difficulty,pressure,4,this.rng);if(e.value<33){p.matchStats.failedControls++;p.matchStats.losses++;this.stats[p.team].controlesRates++;this.stats[p.team].ballonsPerdus++;b.passFrom=null;b.assistCandidate=null;b.pickupDelay=.14;b.vx*=.72;b.vy*=.72;this.emit('CONTROL_FAILED',{team:p.team,player:p.name,skill:p.attributes.technique,context:-difficulty,opposition:pressure,variance:e.variance,score:e.value});return}if(e.value<49){b.x+=b.vx*.055;b.y+=b.vy*.055}}if(p.keeper&&shooter&&shooter.team!==p.team&&speed>120){const positioning=35-Math.abs(p.y-H/2)*.12,needed=speed/18+Math.abs(b.y-H/2)*.18,e=sampleExecution(p.attributes.gardien*.7+p.attributes.vision*.15+p.attributes.vitesse*.1+positioning,-this.fatigue(p),needed,5,this.rng);if(e.value<35)return;p.matchStats.saves++;if(e.value<62||speed>690){p.matchStats.savesParried++;this.stats[p.team].paradesRepoussees++;b.owner=null;b.passFrom=null;b.lastShooter=null;b.pickupDelay=.2;const n=norm(p.x-b.x,p.y-b.y);b.vx=n.x*270;b.vy=n.y*270;this.emit('SAVE_PARRIED',{team:p.team,player:p.name,skill:p.attributes.gardien,opposition:needed,variance:e.variance});return}this.stats[p.team].paradesCaptees++;this.emit('SAVE_CAUGHT',{team:p.team,player:p.name,skill:p.attributes.gardien,opposition:needed,variance:e.variance})}if(passer){if(passer.team===p.team&&passer!==p){passer.matchStats.passesCompleted++;b.assistCandidate=passer;b.assistTime=this.time;this.emit('PASS_COMPLETE',{team:p.team,player:passer.name,target:p.name})}else if(passer.team!==p.team){b.assistCandidate=null;passer.matchStats.losses++;p.matchStats.interceptions++;this.stats[passer.team].ballonsPerdus++;this.stats[p.team].interceptions++;this.emit('INTERCEPTION',{team:p.team,player:p.name})}}if(shooter&&shooter.team!==p.team&&!p.keeper){shooter.matchStats.shotsBlocked++;if(shooter.matchStats.shotsOnTarget){shooter.matchStats.shotsOnTarget--;this.stats[shooter.team].tirsCadres=Math.max(0,this.stats[shooter.team].tirsCadres-1)}this.stats[shooter.team].tirsBloques++;this.emit('SHOT_BLOCKED',{team:p.team,player:p.name})}b.owner=p;b.lastTouch=p.team;b.passFrom=null;if(shooter?.team!==p.team)b.lastShooter=null;p.hasBallTime=0;p.matchStats.touches++}
    goal(team){if(this.freeze>0||this.pendingKickoff)return;this.score[team]++;const scorer=this.ball.lastShooter?.team===team?this.ball.lastShooter:null,assister=scorer&&this.ball.assistCandidate?.team===team&&this.ball.assistCandidate!==scorer&&this.time-this.ball.assistTime<8?this.ball.assistCandidate:null;if(scorer)scorer.matchStats.goals++;if(assister)assister.matchStats.assists++;this.emit('GOAL',{team,player:scorer?.name,assister:assister?.name,score:{...this.score}});this.freeze=2.5;this.pendingKickoff=team==='blue'?'red':'blue';this.ball.vx*=.1;this.ball.vy*=.1}
  }
  function simulateMatch(config={}){const m=new MatchEngine(config);while(!m.isFinished())m.step(config.fixedDt||m.fixedDt);return m.getResult()}
  function simulateMatches(configs=[]){return configs.map(c=>simulateMatch(c))}
  return {MatchEngine,simulateMatch,simulateMatches,RNG,clamp,sigmoid,sampleGaussian,sampleExecution};
});
